### ISSUE TITLE
Initial scope

### ISSUE THREAD

**Issue by BeardedTek** [BeardedTek-com/authelia-manager#1]
Basic user management (VERY basic to start) using argon2id hashes
Basic options in the configuration.yml file

I'm using my personal use case in [this blog post](https://beardedtek.org/traefik-tailscale-linode-dns/) as a starting point of things I want to control (authelia only)

Eventually a configurable endpoint to refresh authelia's config but that's secondary

**Comment by BeardedTek** [comment]
> Eventually a configurable endpoint to refresh authelia's config but that's secondary

As it turns out, there is an option for authelia to watch for changes in its config and reload it automatically:
```
authentication_backend:
  file:
    path: /config/users_database.yml
    watch: true
```
watch: true will set it to reload on detected changes.
